name: Deployment Pipeline
on:
  push:
      branches:
        - main
        - staging
      tags:
        - "*"
  pull_request:
    branches:
      - staging
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "info"
        type: choice
        options:
          - info
          - warning
          - debug
jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set Short SHA as an environment variable
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
          docker tag ${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
          docker push ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Copy config and docker compose to AZURE
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: "deploy/"
          target: "/home/${{ secrets.AZURE_USERNAME }}/nova-server-test"

      - name: SSH into AZURE instance and deploy
        uses: appleboy/ssh-action@v1.0.3
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}
          CONFIG_FILE: "/home/${{ secrets.AZURE_USERNAME }}/nova-server-test/deploy/dev/.env.dev"
          DOCKER_COMPOSE_PATH: "/home/${{ secrets.AZURE_USERNAME }}/nova-server-test/deploy/dev/docker-compose.yml"
          DATABASE_URL: "mysql://${{ secrets.DATABASE_USER }}:${{ secrets.DATABASE_PASSWORD }}@mysql-nova-server:3306/nova"
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          envs: DOCKER_ID,IMAGE_TAG,CONFIG_FILE,DOCKER_COMPOSE_PATH,DATABASE_URL,DOCKER_IMAGE_NAME
          script_stop: true
          script: |
            echo $IMAGE_TAG
            echo $DOCKER_COMPOSE_PATH
            echo $CONFIG_FILE
            sudo docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
            docker compose -f $DOCKER_COMPOSE_PATH down -v
            docker compose -f $DOCKER_COMPOSE_PATH up -d
            sudo docker rmi $(docker image ls -aq) >/dev/null 2>&1 || true